In [12]:
import numpy as np
import pandas as pd
import urllib
import json
import requests
from AEMET_Daily_class import AEMET_GET

In [14]:
years = [2012, 2013, 2014, 2015, 2016, 2017, 2018]
api_key='eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0c3NhbmNoZXpwYXN0b3JAZ21haWwuY29tIiwianRpIjoiYzQzZGM1ZmYtNmRiYS00MzFmLTk3OTEtZWMzNGE3YjUzMDI3IiwiaXNzIjoiQUVNRVQiLCJpYXQiOjE1NjY0Nzc2OTgsInVzZXJJZCI6ImM0M2RjNWZmLTZkYmEtNDMxZi05NzkxLWVjMzRhN2I1MzAyNyIsInJvbGUiOiIifQ.bjmGdiW9vQ2ThnrLryvCxv2tad8XRDXA9zlcBQRg-U4'
fields = ['indicativo', 'fecha', 'tmed', 'dir', 'velmedia', 'presMax', 'presMin']

## Obtain the IDs of the airports

In [15]:
A = AEMET_GET(2012, 2012)
js_stations = A.connect(api_key, 'Station')

{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/6e9ec5e5",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/0556af7a"
}

In [16]:
DF_air = A.get_stations(['BARCELONA', 'ZARAGOZA', 'PAMPLONA', 'HUESCA'], js_stations)
DF_air

    indicativo  latitud longitud                nombre  provincia
140       9898  420504N  001932W     HUESCA AEROPUERTO     HUESCA
219      9263D  424637N  013900W   PAMPLONA AEROPUERTO    NAVARRA
52        0076  411734N  020412E  BARCELONA AEROPUERTO  BARCELONA
289       9434  413938N  010015W   ZARAGOZA AEROPUERTO   ZARAGOZA

In [17]:
IDs, names = DF_air['indicativo'].values, DF_air['provincia'].values

In [18]:
print(IDs, names)

['9898' '9263D' '0076' '9434'] ['HUESCA' 'NAVARRA' 'BARCELONA' 'ZARAGOZA']

In [19]:
def Complete_Dictionary(names, years, IDs, fields):
    i = 0
    DIC = {}
    for ID in IDs:
        name = names[i]
        i += 1
        print('\n\nStation: '+ name)
        for year in years:
            print('Year: {}:'.format(year))
            A = AEMET_GET(year, year)
            js = A.connect(api_key, 'Data', ID)
            DIC[ID + str(year)] = A.get_DF(fields, js)
    return DIC

In [20]:
fields = ['indicativo', 'fecha', 'tmed', 'dir', 'velmedia', 'presMax', 'presMin']
DIC = Complete_Dictionary(names, years, IDs, fields)

Station: HUESCA
Year: 2012:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/5a7ce47f",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2013:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/7c179e28",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2014:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/e0407bdc",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2015:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/48019fe5",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2016:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/7abf83a7",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2017:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/21ee0706",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2018:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/10dae673",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}


Station: NAVARRA
Year: 2012:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/67a2a8e0",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2013:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/d6bc6a45",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2014:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/b34c8689",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2015:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/95d0c18a",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2016:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/97abd184",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2017:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/b1b4a1b2",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2018:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/697e2b69",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}


Station: BARCELONA
Year: 2012:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/0eaa33bd",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2013:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/32559af0",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2014:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/b7f4a4f0",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2015:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/9b0f35e7",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2016:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/94e7e65b",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2017:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/b4c61525",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2018:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/79014212",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}


Station: ZARAGOZA
Year: 2012:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/0edb9997",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2013:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/a76de4f6",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2014:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/3eb02426",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2015:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/7896bf30",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2016:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/c72d2f97",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2017:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/94d7e7dd",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}
Year: 2018:
{
  "descripcion" : "exito",
  "estado" : 200,
  "datos" : "https://opendata.aemet.es/opendata/sh/f675f931",
  "metadatos" : "https://opendata.aemet.es/opendata/sh/b3aa9d28"
}

In [21]:
def concat_dictionary(DIC):
    keys_list = [key for key in DIC.keys()]
    for j in range(len(keys_list)):
        if j == 0:
            Final = DIC[keys_list[0]]
        else:
            Final = pd.concat([Final, DIC[keys_list[j]]])
    return Final

In [69]:
Data = concat_dictionary(DIC)
Data

    indicativo       fecha  tmed   dir  velmedia  presMax  presMin
0         9434  2017-01-01   2.0  12.0       1.7   1000.8    993.0
1         9434  2017-01-02   1.0  30.0       2.2    995.1    992.7
2         9434  2017-01-03   4.0  24.0       2.8    995.0    992.6
3         9434  2017-01-04   6.5  28.0       5.6    995.4    991.9
4         9434  2017-01-05   7.8  30.0      10.8    996.8    991.6
5         9434  2017-01-06   4.0  28.0       3.3   1000.2    996.8
6         9434  2017-01-07   2.6  23.0       1.4   1001.0    998.6
7         9434  2017-01-08   4.6  30.0       5.6   1000.0    995.2
8         9434  2017-01-09   9.2  30.0       9.4    996.8    990.8
9         9434  2017-01-10  10.4  32.0       8.1    990.9    984.2
10        9434  2017-01-11  12.2  31.0       7.8    994.2    986.7
11        9434  2017-01-12  11.7  30.0       2.8    994.3    987.0
12        9434  2017-01-13   7.4  31.0       8.6    994.1    987.6
13        9434  2017-01-14   6.2  30.0       8.6    996.7    993.6
14        9434  2017-01-15   7.3  32.0       7.8    995.8    993.0
15        9434  2017-01-16  10.6  31.0      10.6    993.0    987.8
16        9434  2017-01-17   4.4  33.0      11.7    990.5    986.2
17        9434  2017-01-18   0.6  32.0       5.6    993.9    990.4
18        9434  2017-01-19   1.0  30.0       4.4    994.6    991.1
19        9434  2017-01-20   2.9  29.0       5.6    992.6    990.0
20        9434  2017-01-21   5.6  25.0       3.1    991.3    987.0
21        9434  2017-01-22   6.2  31.0       6.1    988.7    985.8
22        9434  2017-01-23   8.2  31.0       8.1    990.9    987.2
23        9434  2017-01-24   8.2  31.0      10.6    992.6    989.9
24        9434  2017-01-25   4.6  29.0       7.5    991.5    986.4
25        9434  2017-01-26   2.2  11.0       3.1    988.8    983.9
26        9434  2017-01-27   9.8  14.0       4.7    983.9    977.8
27        9434  2017-01-28   8.9  31.0       6.4    994.2    983.0
28        9434  2017-01-29   7.6  10.0       2.5    994.9    991.1
29        9434  2017-01-30  11.2  12.0       1.9    992.4    988.1
..         ...         ...   ...   ...       ...      ...      ...
337       9898  2016-12-03   5.6   9.0       1.9    951.4    950.1
338       9898  2016-12-04  10.1   8.0       4.2    954.0    950.4
339       9898  2016-12-05  11.8   8.0       2.2    959.9    953.8
340       9898  2016-12-06  10.9  24.0       1.1    963.7    959.9
341       9898  2016-12-07   8.6  12.0       1.1    968.3    963.7
342       9898  2016-12-08   4.8  25.0       1.4    969.7    968.3
343       9898  2016-12-09   4.6  32.0       1.4    969.7    965.5
344       9898  2016-12-10   2.8  99.0       0.8    965.5    962.5
345       9898  2016-12-11   2.7  28.0       0.8    962.6    958.9
346       9898  2016-12-12   2.2  13.0       1.1    960.1    958.2
347       9898  2016-12-13   2.6  10.0       1.4    960.0    958.8
348       9898  2016-12-14   4.5   8.0       1.9    958.8    955.9
349       9898  2016-12-15   6.1  11.0       1.7    957.2    955.3
350       9898  2016-12-16   8.2  11.0       3.3    962.6    953.5
351       9898  2016-12-17   9.0  11.0       1.1    968.1    962.6
352       9898  2016-12-18   6.6   4.0       1.4    968.1    958.8
353       9898  2016-12-19   2.0  29.0       1.4    958.8    949.4
354       9898  2016-12-20   4.3  26.0       1.1    957.2    949.4
355       9898  2016-12-21   3.8   9.0       1.4    965.0    957.1
356       9898  2016-12-22   4.8  24.0       1.1    969.3    964.6
357       9898  2016-12-23   5.0  31.0       1.1    970.0    969.0
358       9898  2016-12-24   4.4   9.0       1.4    970.8    970.0
359       9898  2016-12-25   3.8  32.0       1.1    970.5    966.0
360       9898  2016-12-26   2.6  29.0       1.1    967.3    965.9
361       9898  2016-12-27   2.6  14.0       0.8    970.4    966.9
362       9898  2016-12-28   0.1  26.0       1.4    972.2    969.4
363       9898  2016-12-29  -2.0  27.0       1.7    969.6    966.9
364       9898  2016-12-30  -1.1   8.0       0.6    971.0    968.3
365       9898  2016-12-31   0.8  21.0       1.4    968.7    964.5
366       9898  2017-01-01  -0.5  13.0       0.8    964.5    957.1

[10256 rows x 7 columns]

In [70]:
print(Data.describe())

               tmed          dir      velmedia       presMax       presMin
count  10198.000000  9948.000000  10201.000000  10201.000000  10200.000000
mean      15.499853    38.746482      4.080227    982.983962    978.189716
std        7.131276    31.702315      2.328423     24.947490     25.084331
min       -3.400000     1.000000      0.000000    931.300000    918.000000
25%        9.800000    20.000000      2.500000    961.200000    956.475000
50%       15.100000    29.000000      3.600000    979.200000    974.000000
75%       21.400000    35.000000      5.300000   1003.900000    998.600000
max       33.800000    99.000000     16.100000   1040.900000   1035.900000

In [71]:
print("How many null ar in the dataset? ", Data.isnull().sum())

How many null ar in the dataset?  indicativo      0
fecha           0
tmed           58
dir           308
velmedia       55
presMax        55
presMin        56
dtype: int64

In [72]:
def filter_duplicates(DF):
    duplicated = DF.duplicated()
    filter_duplicates = DF.duplicated(keep='first')
    return Data[~filter_duplicates]

In [73]:
Data = filter_duplicates(Data)

In [81]:
Data.sort_values('fecha').to_csv('~/Rn_Weekly_NN/AEMET/Data/Daily/BCN_ZGZ_PMP_Huesca_Daily' + str(years[0]) + '-' + str(years[-1]) + '.csv')

In [82]:
Data.describe()

               tmed          dir      velmedia       presMax       presMin
count  10174.000000  9925.000000  10177.000000  10177.000000  10176.000000
mean      15.520012    38.746599      4.081321    982.969166    978.179766
std        7.125933    31.699080      2.328587     24.944659     25.083108
min       -3.400000     1.000000      0.000000    931.300000    918.000000
25%        9.800000    20.000000      2.500000    961.200000    956.400000
50%       15.200000    29.000000      3.600000    979.200000    974.000000
75%       21.400000    35.000000      5.300000   1003.800000    998.600000
max       33.800000    99.000000     16.100000   1040.900000   1035.900000

In [83]:
len(Data['fecha'])

10232

In [105]:
(365 * 7 + 2 + 1)*4
# 365 days + 2 bisiestos + 1 from 2019 multiplied by 4 stations

10232

In [85]:
duplicated = Data.duplicated()